9- Manage content
Create and use templates to create customized configuration files
Use Ansible Vault in playbooks to protect sensitive data

PARRALLELISM
forks = 50 (how many simultaneous processes should control node start)
how many nodes a task is being executed on at a time
  hosts: vmservers
  serial:
    - 1
    - 2
    - 50%
  tasks:
first run all tasks on server 1, then 2, then 50% of all left
"********************************************************************************"
VAULT
{TASK1}
[ansible@x230 automation]$ vim playbooks/ansible_vault.yml
---
- name: Ansible Vault Playbook
  hosts: web
  vars:
    pw: redhat
  tasks:
    - name: Creating user account and password
      user:
        name: trump
        password: "{{ pw }}"

ansible-vault encrypt playbook/ansible_vault.yml
[ansible@x230 automation]$ ansible-vault encrypt playbooks/ansible_vault.yml
New Vault password:
Confirm New Vault password:
Encryption successful
[ansible@x230 automation]$ cat playbooks/ansible_vault.yml
$ANSIBLE_VAULT;1.1;AES256
#Adv Encryption Standard - 256 bit key used to convert text into cipher


encrypt whole file
[ansible@x230 automation]$ ansible-playbook playbooks/ansible_vault.yml --ask-vault-password
[ansible@x230 automation]$ ansible-vault edit playbook/ansible_vault.yml

encrypt only a variable and call it from encrypted file
[ansible@x230 automation]$ ansible-vault view playbook/ansible_vault2.yml
[ansible@x230 automation]$ ansible-vault create ~/crypt.yml
[ansible@x230 automation]$ ansible-vault rekey ~/crypt.yml

save password in a file
[ansible@x230 automation]$ ansible-vault encrypt playbook/ansible_vault3.yml
passowrd: redhat
vim pass.txt 
redhat
[ansible@x230 automation]$ ansible-playbook playbooks/ansible_vault3.yml 
                          "--vault-password-file" pass.txt

encrypt a string
[ansible@x230 automation]$ ansible-vault encrypt_string 'bar' --name 'foo'
foo has been encrypted as bar
[ansible@x230 automation]$ ansible-vault encrypt_string 'bar' --name 'foo' > bar.txt
ansible-vault encrypt_string --ask-vault-pass '8080' --name 'http_port'

Prompt for a Password with Vault-id
ansible-playbook --vault-id label@prompt playbook.yml

Prompt for two Passwords with Vault-id
ansible-playbook --vault-id label@prompt --vault-id label2@prompt playbook.yml