version: 0.2

phases:
  install:
    runtime-versions:
       python: 3.8
  build:
    commands:
      - pip install aws-sam-cli
      - sam build -t sam-app/template.yaml
      - sam package --template-file sam-app/template.yaml --output-template-file outputtemplate.yaml --s3-bucket sam-app329329
artifacts:
  files: 
    - outputtemplate.yaml